// Records the audit_logs high-water mark before any test runs. expense.spec.ts
// deletes the transaction it creates, but the recordAudit entries persist by
// design; global-teardown uses this baseline to remove only the audit rows
// generated by this run, leaving pre-existing audit history untouched.
//
// Uses the @ultra-light/db package (which wires the PrismaPg driver adapter and
// reads DATABASE_URL). The dynamic import runs *after* loadEnvFile so the db
// singleton sees DATABASE_URL at module-init time.
export default async function globalSetup() {
  process.loadEnvFile(".env");
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not set");
  }

  const { db } = await import("@ultra-light/db");
  try {
    const result = await db.auditLog.aggregate({ _max: { id: true } });
    process.env.E2E_AUDIT_BASELINE_ID = String(result._max.id ?? 0);
  } finally {
    await db.$disconnect();
  }
}
