import { PrismaPg } from "@prisma/adapter-pg";

import { PrismaClient } from "../packages/db/src/generated/client";

// Records the audit_logs high-water mark before any test runs. expense.spec.ts
// deletes the transaction it creates, but the recordAudit entries persist by
// design; global-teardown uses this baseline to remove only the audit rows
// generated by this run, leaving pre-existing audit history untouched.
export default async function globalSetup() {
  process.loadEnvFile(".env");
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error("DATABASE_URL is not set");
  }

  const adapter = new PrismaPg({ connectionString: databaseUrl, max: 1 });
  const db = new PrismaClient({ adapter });
  try {
    const result = await db.auditLog.aggregate({ _max: { id: true } });
    process.env.E2E_AUDIT_BASELINE_ID = String(result._max.id ?? 0);
  } finally {
    await db.$disconnect();
  }
}
